#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ItiClone.Droid.Resource", IsApplication=true)]

namespace ItiClone.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int cartaocreditoicon = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int colocardinheiroicon = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int diasdamaesconexaoicon = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int itauconexaoicon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int itiicon = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int itiicon1 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int locationicon = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int mycardsicon = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int pagaricon = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int pencilicon = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int qrcodeicon = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int recargaicon = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int recommendationicon = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int shopclubconexaoicon = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int sincardiconorange = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int sincardiconwhite = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int usericon = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int sliding_tabs = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int toolbar = 2130903041;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Tabbar = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Toolbar = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int icon = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int icon_round = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int launcher_foreground = 2131034114;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppCompatDialogStyle = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int MainTheme = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int MainTheme_Base = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
